version: 2.1

default_runner: &default_runner
  docker: 
    - image: cimg/node:13.8.0
      
jobs:
  build:
    <<: *default_runner 
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - save_cache:
          key: "npm-packages"
          paths: 
            - /src/node_modules
  test:
    <<: *default_runner 
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "npm-packages"
      - run: npm i 
      - run: npm run test

  analyze: 
    <<: *default_runner 
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "npm-packages"
      - run: npm audit
        

workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test          
